# https://github.com/elastic/beats-docker
FROM docker.elastic.co/beats/filebeat:6.2.2

#USER
# RUN sudo groupadd becloodusers --gid=1000
# RUN useradd -ms /bin/bash beclood --uid=1000 --gid=1000 --home-dir=/home/beclood

# https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html

# Add your filebeat plugins setup here
# Example: RUN kibana-plugin install <name|url>

# RUN echo "PS1='\[\e[36;43m\]DOCKER FILEBEAT\[\e[m\] ${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> /root/.bashrc
# RUN echo "alias ll='ls -alF'" >> /root/.bashrc