# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.2.1

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

# RUN echo "PS1='\[\e[36;43m\]DOCKER KIBANA\[\e[m\] ${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> /root/.bashrc
# RUN echo "alias ll='ls -alF'" >> /root/.bashrc